package com.videlilja.linda.lia.model;

public enum Categories {
    ADDITION, SUBTRACTION, MULTIPLICATION, DIVISION, GEOMETRY,
    BIRDS, MAMMALS,
    FLOWERS, HERBS,
    AFRICA, EUROPE, ASIA, OCEANIA, NORTH_AMERICA, SOUTH_AMERICA,
    PIC_TO_WORD, WORD_TO_PIC, SPELLING
}
