package com.videlilja.linda.lia.model;

public enum Categories {
    BIRDS, MAMMALS,
    FLOWERS, HERBS,
    ADDITION, SUBTRACTION, MULTIPLICATION, DIVISION,
    F_AFRICA, F_EUROPE, F_ASIA, F_OCEANIA, F_NORTH_AMERICA, F_SOUTH_AMERICA,
    C_AFRICA, C_EUROPE, C_ASIA, C_OCEANIA, C_NORTH_AMERICA, C_SOUTH_AMERICA,
    PIC_TO_WORD, WORD_TO_PIC
}
